-- 自動生成: python3 tools/gen_seed_sql.py
-- 手で編集しない。元データは data/curriculum/ と data/templates/
begin;
delete from templates; delete from learning_items; delete from units;
insert into units (id, grade, domain, name, seq) values ('M1-A1', 1, 'A', '正の数と負の数', 1);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A1-K1', 'M1-A1', 'knowledge', 1, '正の数と負の数の必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A1-K2', 'M1-A1', 'knowledge', 2, '正の数と負の数の四則計算をすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A1-K3', 'M1-A1', 'knowledge', 3, '具体的な場面で正の数と負の数を用いて表したり処理したりすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A1-T1', 'M1-A1', 'thinking', 1, '算数で学習した数の四則計算と関連付けて、正の数と負の数の四則計算の方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A1-T2', 'M1-A1', 'thinking', 2, '正の数と負の数を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M1-A2', 1, 'A', '文字を用いた式', 2);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A2-K1', 'M1-A2', 'knowledge', 1, '文字を用いることの必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A2-K2', 'M1-A2', 'knowledge', 2, '文字を用いた式における乗法と除法の表し方を知ること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A2-K3', 'M1-A2', 'knowledge', 3, '簡単な一次式の加法と減法の計算をすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A2-K4', 'M1-A2', 'knowledge', 4, '数量の関係や法則などを文字を用いた式に表すことができることを理解し、式を用いて表したり読み取ったりすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A2-T1', 'M1-A2', 'thinking', 1, '具体的な場面と関連付けて、一次式の加法と減法の計算の方法を考察し表現すること');
insert into units (id, grade, domain, name, seq) values ('M1-A3', 1, 'A', '一元一次方程式', 3);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A3-K1', 'M1-A3', 'knowledge', 1, '方程式の必要性と意味及び方程式の中の文字や解の意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A3-K2', 'M1-A3', 'knowledge', 2, '簡単な一元一次方程式を解くこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A3-T1', 'M1-A3', 'thinking', 1, '等式の性質を基にして、一元一次方程式を解く方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-A3-T2', 'M1-A3', 'thinking', 2, '一元一次方程式を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M1-B1', 1, 'B', '平面図形', 4);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B1-K1', 'M1-B1', 'knowledge', 1, '角の二等分線、線分の垂直二等分線、垂線などの基本的な作図の方法を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B1-K2', 'M1-B1', 'knowledge', 2, '平行移動、対称移動及び回転移動について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B1-T1', 'M1-B1', 'thinking', 1, '図形の性質に着目し、基本的な作図の方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B1-T2', 'M1-B1', 'thinking', 2, '図形の移動に着目し、二つの図形の関係について考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B1-T3', 'M1-B1', 'thinking', 3, '基本的な作図や図形の移動を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M1-B2', 1, 'B', '空間図形', 5);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B2-K1', 'M1-B2', 'knowledge', 1, '空間における直線や平面の位置関係を知ること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B2-K2', 'M1-B2', 'knowledge', 2, '扇形の弧の長さと面積、基本的な柱体や錐体、球の表面積と体積を求めること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B2-T1', 'M1-B2', 'thinking', 1, '空間図形を直線や平面図形の運動によって構成されるものと捉えたり、空間図形を平面上に表現して平面上の表現から空間図形の性質を見いだしたりすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-B2-T2', 'M1-B2', 'thinking', 2, '立体図形の表面積や体積の求め方を考察し表現すること');
insert into units (id, grade, domain, name, seq) values ('M1-C1', 1, 'C', '比例、反比例', 6);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-C1-K1', 'M1-C1', 'knowledge', 1, '関数関係の意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-C1-K2', 'M1-C1', 'knowledge', 2, '比例、反比例について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-C1-K3', 'M1-C1', 'knowledge', 3, '座標の意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-C1-K4', 'M1-C1', 'knowledge', 4, '比例、反比例を表、式、グラフなどに表すこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-C1-T1', 'M1-C1', 'thinking', 1, '比例、反比例として捉えられる二つの数量について、表、式、グラフなどを用いて調べ、それらの変化や対応の特徴を見いだすこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-C1-T2', 'M1-C1', 'thinking', 2, '比例、反比例を用いて具体的な事象を捉え考察し表現すること');
insert into units (id, grade, domain, name, seq) values ('M1-D1', 1, 'D', 'データの分布', 7);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-D1-K1', 'M1-D1', 'knowledge', 1, 'ヒストグラムや相対度数などの必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-D1-K2', 'M1-D1', 'knowledge', 2, 'コンピュータなどの情報手段を用いるなどしてデータを表やグラフに整理すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-D1-T1', 'M1-D1', 'thinking', 1, '目的に応じてデータを収集して分析し、そのデータの分布の傾向を読み取り、批判的に考察し判断すること');
insert into units (id, grade, domain, name, seq) values ('M1-D2', 1, 'D', '不確定な事象の起こりやすさ', 8);
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-D2-K1', 'M1-D2', 'knowledge', 1, '多数の観察や多数回の試行によって得られる確率の必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M1-D2-T1', 'M1-D2', 'thinking', 1, '多数の観察や多数回の試行の結果を基にして、不確定な事象の起こりやすさの傾向を読み取り表現すること');
insert into units (id, grade, domain, name, seq) values ('M2-A1', 2, 'A', '文字を用いた式', 9);
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A1-K1', 'M2-A1', 'knowledge', 1, '簡単な整式の加法と減法及び単項式の乗法と除法の計算をすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A1-K2', 'M2-A1', 'knowledge', 2, '具体的な事象の中の数量の関係を文字を用いた式で表したり、式の意味を読み取ったりすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A1-K3', 'M2-A1', 'knowledge', 3, '文字を用いた式で数量及び数量の関係を捉え説明できることを理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A1-K4', 'M2-A1', 'knowledge', 4, '目的に応じて、簡単な式を変形すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A1-T1', 'M2-A1', 'thinking', 1, '具体的な数の計算や既に学習した計算の方法と関連付けて、整式の加法と減法及び単項式の乗法と除法の計算の方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A1-T2', 'M2-A1', 'thinking', 2, '文字を用いた式を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M2-A2', 2, 'A', '連立二元一次方程式', 10);
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A2-K1', 'M2-A2', 'knowledge', 1, '二元一次方程式とその解の意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A2-K2', 'M2-A2', 'knowledge', 2, '連立二元一次方程式の必要性と意味及びその解の意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A2-K3', 'M2-A2', 'knowledge', 3, '簡単な連立二元一次方程式を解くこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A2-T1', 'M2-A2', 'thinking', 1, '一元一次方程式と関連付けて、連立二元一次方程式を解く方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-A2-T2', 'M2-A2', 'thinking', 2, '連立二元一次方程式を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M2-B1', 2, 'B', '基本的な平面図形の性質', 11);
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-B1-K1', 'M2-B1', 'knowledge', 1, '平行線や角の性質を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-B1-K2', 'M2-B1', 'knowledge', 2, '多角形の角についての性質が見いだせることを知ること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-B1-T1', 'M2-B1', 'thinking', 1, '基本的な平面図形の性質を見いだし、平行線や角の性質を基にしてそれらを確かめ説明すること');
insert into units (id, grade, domain, name, seq) values ('M2-B2', 2, 'B', '図形の合同', 12);
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-B2-K1', 'M2-B2', 'knowledge', 1, '平面図形の合同の意味及び三角形の合同条件について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-B2-K2', 'M2-B2', 'knowledge', 2, '証明の必要性と意味及びその方法について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-B2-T1', 'M2-B2', 'thinking', 1, '三角形の合同条件などを基にして三角形や平行四辺形の基本的な性質を論理的に確かめたり、証明を読んで新たな性質を見いだしたりすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-B2-T2', 'M2-B2', 'thinking', 2, '三角形や平行四辺形の基本的な性質などを具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M2-C1', 2, 'C', '一次関数', 13);
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-C1-K1', 'M2-C1', 'knowledge', 1, '一次関数について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-C1-K2', 'M2-C1', 'knowledge', 2, '事象の中には一次関数として捉えられるものがあることを知ること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-C1-K3', 'M2-C1', 'knowledge', 3, '二元一次方程式を関数を表す式とみること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-C1-T1', 'M2-C1', 'thinking', 1, '一次関数として捉えられる二つの数量について、変化や対応の特徴を見いだし、表、式、グラフを相互に関連付けて考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-C1-T2', 'M2-C1', 'thinking', 2, '一次関数を用いて具体的な事象を捉え考察し表現すること');
insert into units (id, grade, domain, name, seq) values ('M2-D1', 2, 'D', 'データの分布', 14);
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-D1-K1', 'M2-D1', 'knowledge', 1, '四分位範囲や箱ひげ図の必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-D1-K2', 'M2-D1', 'knowledge', 2, 'コンピュータなどの情報手段を用いるなどしてデータを整理し箱ひげ図で表すこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-D1-T1', 'M2-D1', 'thinking', 1, '四分位範囲や箱ひげ図を用いてデータの分布の傾向を比較して読み取り、批判的に考察し判断すること');
insert into units (id, grade, domain, name, seq) values ('M2-D2', 2, 'D', '不確定な事象の起こりやすさ', 15);
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-D2-K1', 'M2-D2', 'knowledge', 1, '多数回の試行によって得られる確率と関連付けて、場合の数を基にして得られる確率の必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-D2-K2', 'M2-D2', 'knowledge', 2, '簡単な場合について確率を求めること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-D2-T1', 'M2-D2', 'thinking', 1, '同様に確からしいことに着目し、場合の数を基にして得られる確率の求め方を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M2-D2-T2', 'M2-D2', 'thinking', 2, '確率を用いて不確定な事象を捉え考察し表現すること');
insert into units (id, grade, domain, name, seq) values ('M3-A1', 3, 'A', '正の数の平方根', 16);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A1-K1', 'M3-A1', 'knowledge', 1, '数の平方根の必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A1-K2', 'M3-A1', 'knowledge', 2, '数の平方根を含む簡単な式の計算をすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A1-K3', 'M3-A1', 'knowledge', 3, '具体的な場面で数の平方根を用いて表したり処理したりすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A1-T1', 'M3-A1', 'thinking', 1, '既に学習した計算の方法と関連付けて、数の平方根を含む式の計算の方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A1-T2', 'M3-A1', 'thinking', 2, '数の平方根を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M3-A2', 3, 'A', '簡単な多項式', 17);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A2-K1', 'M3-A2', 'knowledge', 1, '単項式と多項式の乗法及び多項式を単項式で割る除法の計算をすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A2-K2', 'M3-A2', 'knowledge', 2, '簡単な一次式の乗法の計算及び公式 (a+b)²=a²+2ab+b² / (a−b)²=a²−2ab+b² / (a+b)(a−b)=a²−b² / (x+a)(x+b)=x²+(a+b)x+ab を用いる簡単な式の展開や因数分解をすること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A2-T1', 'M3-A2', 'thinking', 1, '既に学習した計算の方法と関連付けて、式の展開や因数分解をする方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A2-T2', 'M3-A2', 'thinking', 2, '文字を用いた式で数量及び数量の関係を捉え説明すること');
insert into units (id, grade, domain, name, seq) values ('M3-A3', 3, 'A', '二次方程式', 18);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A3-K1', 'M3-A3', 'knowledge', 1, '二次方程式の必要性と意味及びその解の意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A3-K2', 'M3-A3', 'knowledge', 2, '因数分解したり平方の形に変形したりして二次方程式を解くこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A3-K3', 'M3-A3', 'knowledge', 3, '解の公式を知り、それを用いて二次方程式を解くこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A3-T1', 'M3-A3', 'thinking', 1, '因数分解や平方根の考えを基にして、二次方程式を解く方法を考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-A3-T2', 'M3-A3', 'thinking', 2, '二次方程式を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M3-B1', 3, 'B', '図形の相似', 19);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B1-K1', 'M3-B1', 'knowledge', 1, '平面図形の相似の意味及び三角形の相似条件について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B1-K2', 'M3-B1', 'knowledge', 2, '基本的な立体の相似の意味及び相似な図形の相似比と面積比や体積比との関係について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B1-T1', 'M3-B1', 'thinking', 1, '三角形の相似条件などを基にして図形の基本的な性質を論理的に確かめること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B1-T2', 'M3-B1', 'thinking', 2, '平行線と線分の比についての性質を見いだし、それらを確かめること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B1-T3', 'M3-B1', 'thinking', 3, '相似な図形の性質を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M3-B2', 3, 'B', '円周角と中心角の関係', 20);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B2-K1', 'M3-B2', 'knowledge', 1, '円周角と中心角の関係の意味を理解し、それが証明できることを知ること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B2-T1', 'M3-B2', 'thinking', 1, '円周角と中心角の関係を見いだすこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B2-T2', 'M3-B2', 'thinking', 2, '円周角と中心角の関係を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M3-B3', 3, 'B', '三平方の定理', 21);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B3-K1', 'M3-B3', 'knowledge', 1, '三平方の定理の意味を理解し、それが証明できることを知ること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B3-T1', 'M3-B3', 'thinking', 1, '三平方の定理を見いだすこと');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-B3-T2', 'M3-B3', 'thinking', 2, '三平方の定理を具体的な場面で活用すること');
insert into units (id, grade, domain, name, seq) values ('M3-C1', 3, 'C', '関数 y=ax²', 22);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-C1-K1', 'M3-C1', 'knowledge', 1, '関数 y=ax² について理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-C1-K2', 'M3-C1', 'knowledge', 2, '事象の中には関数 y=ax² として捉えられるものがあることを知ること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-C1-K3', 'M3-C1', 'knowledge', 3, 'いろいろな事象の中に、関数関係があることを理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-C1-T1', 'M3-C1', 'thinking', 1, '関数 y=ax² として捉えられる二つの数量について、変化や対応の特徴を見いだし、表、式、グラフを相互に関連付けて考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-C1-T2', 'M3-C1', 'thinking', 2, '関数 y=ax² を用いて具体的な事象を捉え考察し表現すること');
insert into units (id, grade, domain, name, seq) values ('M3-D1', 3, 'D', '標本調査', 23);
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-D1-K1', 'M3-D1', 'knowledge', 1, '標本調査の必要性と意味を理解すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-D1-K2', 'M3-D1', 'knowledge', 2, 'コンピュータなどの情報手段を用いるなどして無作為に標本を取り出し、整理すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-D1-T1', 'M3-D1', 'thinking', 1, '標本調査の方法や結果を批判的に考察し表現すること');
insert into learning_items (id, unit_id, kind, seq, text) values ('M3-D1-T2', 'M3-D1', 'thinking', 2, '簡単な場合について標本調査を行い、母集団の傾向を推定し判断すること');
insert into templates (id, item_id, format, difficulty, title, spec, status) values ('T-M1-A1-001', 'M1-A1-K2', 'numeric', 1, '正負の数の加法', '{"id": "T-M1-A1-001", "item": "M1-A1", "item_kind": "knowledge", "item_index": 2, "format": "numeric", "difficulty": 1, "title": "正負の数の加法", "variables": {"a": {"type": "int", "min": -9, "max": 9, "exclude": [0]}, "b": {"type": "int", "min": -9, "max": 9, "exclude": [0]}}, "constraints": ["a + b != 0"], "derived": {"ans": "a + b"}, "body": "次の計算をしなさい。\n{a} + ({b})\n", "answers": {"答え": "ans"}, "explanation": "同符号の2数の和は、絶対値の和に共通の符号を付けます。\n異符号の2数の和は、絶対値の差に絶対値の大きい方の符号を付けます。\n{a} + ({b}) = {ans}\n", "status": "draft"}'::jsonb, 'draft');
insert into templates (id, item_id, format, difficulty, title, spec, status) values ('T-M2-A2-001', 'M2-A2-K3', 'numeric', 2, '連立方程式（加減法）', '{"id": "T-M2-A2-001", "item": "M2-A2", "item_kind": "knowledge", "item_index": 3, "format": "numeric", "difficulty": 2, "title": "連立方程式（加減法）", "variables": {"x0": {"type": "int", "min": -5, "max": 5}, "y0": {"type": "int", "min": -5, "max": 5, "exclude": [0]}, "a1": {"type": "int", "min": 1, "max": 4}, "b1": {"type": "int", "min": 1, "max": 4}, "a2": {"type": "int", "min": 1, "max": 4}, "b2": {"type": "int", "min": -4, "max": -1}}, "constraints": ["a1 * b2 - a2 * b1 != 0", "x0 != y0"], "derived": {"c1": "a1 * x0 + b1 * y0", "c2": "a2 * x0 + b2 * y0"}, "body": "次の連立方程式を解きなさい。\n{a1}x + {b1}y = {c1}\n{a2}x + ({b2})y = {c2}\n", "answers": {"x": "x0", "y": "y0"}, "explanation": "加減法で文字を消去して解きます。\n2つの式を組み合わせて y（または x）を消去し、残った一次方程式を解くと\nx = {x0} が得られます。これを一方の式に代入すると y = {y0} となります。\n答え: x = {x0}, y = {y0}\n", "status": "draft"}'::jsonb, 'draft');
insert into templates (id, item_id, format, difficulty, title, spec, status) values ('T-M2-B2-001', 'M2-B2-K1', 'choice', 1, '三角形の合同条件（穴埋め選択）', '{"id": "T-M2-B2-001", "item": "M2-B2", "item_kind": "knowledge", "item_index": 1, "format": "choice", "difficulty": 1, "title": "三角形の合同条件（穴埋め選択）", "variables": {"q": {"type": "int", "min": 1, "max": 3}}, "constraints": [], "derived": {}, "case_var": "q", "body_by_case": {"1": "三角形の合同条件について、□にあてはまるものを選びなさい。\n「3組の□がそれぞれ等しいとき、2つの三角形は合同である。」\n", "2": "三角形の合同条件について、□にあてはまるものを選びなさい。\n「2組の辺とその□がそれぞれ等しいとき、2つの三角形は合同である。」\n", "3": "三角形の合同条件について、□にあてはまるものを選びなさい。\n「1組の辺とその□がそれぞれ等しいとき、2つの三角形は合同である。」\n"}, "correct_by_case": {"1": "辺", "2": "間の角", "3": "両端の角"}, "distractors_by_case": {"1": ["角", "間の角", "両端の角"], "2": ["両端の角", "対角", "辺"], "3": ["間の角", "対角", "辺"]}, "explanation": "三角形の合同条件は次の3つです。\n1. 3組の辺がそれぞれ等しい（三辺相等）\n2. 2組の辺とその間の角がそれぞれ等しい（二辺夾角相等）\n3. 1組の辺とその両端の角がそれぞれ等しい（一辺両端角相等）\n", "status": "draft"}'::jsonb, 'draft');
insert into templates (id, item_id, format, difficulty, title, spec, status) values ('T-M2-C1-001', 'M2-C1-K1', 'numeric', 1, '一次関数の変化の割合', '{"id": "T-M2-C1-001", "item": "M2-C1", "item_kind": "knowledge", "item_index": 1, "format": "numeric", "difficulty": 1, "title": "一次関数の変化の割合", "variables": {"m": {"type": "int", "min": -4, "max": 4, "exclude": [0]}, "n": {"type": "int", "min": -5, "max": 5}, "x1": {"type": "int", "min": -4, "max": 2}, "d": {"type": "int", "min": 1, "max": 5}}, "constraints": [], "derived": {"x2": "x1 + d", "y1": "m * x1 + n", "y2": "m * (x1 + d) + n"}, "body": "ある一次関数について、x = {x1} のとき y = {y1}、x = {x2} のとき y = {y2} です。\nこの一次関数の変化の割合を求めなさい。\n", "answers": {"変化の割合": "m"}, "explanation": "変化の割合 = (yの増加量) ÷ (xの増加量) です。\nyの増加量: {y2} - ({y1})\nxの増加量: {x2} - ({x1}) = {d}\nよって 変化の割合 = {m}\n", "status": "draft"}'::jsonb, 'draft');
commit;
